### ISSUE TITLE
Lil_Soundie_Audio_Player

### ISSUE THREAD

**Issue by sidh15** [sparkfun/Lil_Soundie_Audio_Player#6]
I want to make Lil_Soundie_Audio_Player on a very small board size. Is it possible to make same kind of functionality on the possible smaller size with component?
If yes, what programming are required on the board, if I am buying components separately?                                                                                                                                                                                         I am thinking to place this IC LE25U40CMD from ON semiconductor, will it be compatible for small storage of audio size 150 KB.

**Comment by bboyho** [comment]
Hi,

It should be possible to make the board smaller. You should check out the resources provided by the company that manufactures the IC for more information on how to program the IC. There is detailed information available on how to program the chip with the software via USB on the VS1000's product page => [ [http://www.vlsi.fi/en/products/vs1000.html](http://www.vlsi.fi/en/products/vs1000.html) ]. Our hookup guide states that we use the VSIDE software. 

As far as the LE25U40CMD IC, this question seems to be out of scope of the product itself and not an issue related with the Lil' Soundie Audio Player. What I can say is that it looks like a SPI serial flash memory similar to the one that is on the Lil' Soundie Audio Player. However, I do not have as much experience with the chip and VS1000D. You should check out the resources linked for more information or check out the [VLSI support forums](http://www.vsdsp-forum.com/phpbb/).
